In [1]:
import numpy as np
from scipy.sparse import csr_matrix
  
sparseMatrix = csr_matrix((4, 4), dtype = np.int8).toarray()  
print(sparseMatrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [2]:
row = np.array([0,0,1,1,3,3,])
col = np.array([2,4,2,3,1,2])
data = np.array([3,4,5,7,2,6])
  
sparseMatrix = csr_matrix((data, (row, col)), shape = (4, 5)).toarray()    
print(sparseMatrix)

[[0 0 3 0 4]
 [0 0 5 7 0]
 [0 0 0 0 0]
 [0 2 6 0 0]]
